1082 rh UI implement pages and logic from old rh
ONSdigital/srm-rh-ui pull request #3
Opened 2023-08-22 14:39 UTC by ryangrundy7

# Motivation and Context

Now that we've got the base for the new rh-ui, we need to implement the rest of the logic and pages that RH-UI needs.
# What has changed

- Added all templates from old rh-ui
- Launch a survey
- Added welsh translations
- Translation logic simplified compared to old RH
- Error handling copied over from rh-ui 
# How to test?

- Bring up Docker-dev and stop the old rh-ui
- Run this branch against docker-dev
- Launch a survey
- Check all error routes (404, invalid uac length, invalid uac, no uac entered, Connection error to rh-service)
- Check all page links work as expected.
- Check all welsh translations work
- Run unit tests 
# Links

[Trello](https://trello.com/c/BkGDjNN4/)

2023-08-24 11:19 UTC, hbrace reviewed
Not really a comment on your work, but would it make sense for the `make install` command to include the pipenv install and load_templates?

2023-08-30 14:59 UTC, gavinleeedwards requested changes
Functionally, it all works good.  Just a few minor comments.  

The formatting on all pages is slightly different to the current rh-ui (comparing it to what we have in preprod).  The text and elements now stretch across the length of the page.  It's a definite difference but does is matter from a UI perspective?

2023-08-30 14:59 UTC, gavinleeedwards commented on rh_ui/templates/info_pages/privacy-and-data-protection.html
> +                        by the<a href="https://code.statisticsauthority.gov.uk/"> Code of Practice for Statistics</a>')
The links on this page should all open in a new tab.

2023-08-31 10:06 UTC, ryangrundy7 commented on rh_ui/logger_config.py
>  from structlog.threadlocal import wrap_dict
Good spot. I'll take a look into it

2023-08-31 14:46 UTC, gavinleeedwards approved these changes

2023-09-01 08:07 UTC, hbrace approved these changes

2023-09-01 13:21 UTC, merged